### ISSUE TITLE
Утечка памяти на клиенте

### ISSUE THREAD

**Issue by DaftTrick** [ONLYOFFICE/testing-wrata#56]
Примерно за 4 часа цпу и память под 100% съедаются владкой с раннером
![image](https://cloud.githubusercontent.com/assets/6764185/8672358/2b3f5e0e-2a36-11e5-8d94-976f4449c1ae.png)

**Comment by ShockwaveNN** [comment]
A lot of code was redone so I'm not sure that this problem is actual
